-- Mise à jour des classes (si base déjà importée)
-- phpMyAdmin → Exécuter ce script

DELETE FROM classes;

INSERT INTO `classes` (`nom`, `section`, `ordre`) VALUES
('1ère maternelle', 'Maternelle', 1),
('2ème maternelle', 'Maternelle', 2),
('3ème maternelle', 'Maternelle', 3),
('1ère primaire', 'Primaire', 10),
('2ème primaire', 'Primaire', 11),
('3ème primaire', 'Primaire', 12),
('4ème primaire', 'Primaire', 13),
('5ème primaire', 'Primaire', 14),
('6ème primaire', 'Primaire', 15),
('7ème', 'Secondaire', 20),
('8ème', 'Secondaire', 21),
('1ère pédagogie', 'Pédagogie', 30),
('2ème pédagogie', 'Pédagogie', 31),
('3ème pédagogie', 'Pédagogie', 32),
('4ème pédagogie', 'Pédagogie', 33),
('1ère pétrochimie', 'Pétrochimie', 40),
('2ème pétrochimie', 'Pétrochimie', 41),
('3ème pétrochimie', 'Pétrochimie', 42),
('4ème pétrochimie', 'Pétrochimie', 43),
('1ère commercial', 'Commercial', 50),
('2ème commercial', 'Commercial', 51),
('3ème commercial', 'Commercial', 52),
('4ème commercial', 'Commercial', 53),
('1ère électronique', 'Électronique', 60),
('2ème électronique', 'Électronique', 61),
('3ème électronique', 'Électronique', 62),
('4ème électronique', 'Électronique', 63),
('1ère science', 'Science', 70),
('2ème science', 'Science', 71),
('3ème science', 'Science', 72),
('4ème science', 'Science', 73),
('1ère électricité', 'Électricité', 80),
('2ème électricité', 'Électricité', 81),
('3ème électricité', 'Électricité', 82),
('4ème électricité', 'Électricité', 83),
('1ère mécanique auto', 'Mécanique Auto', 90),
('2ème mécanique auto', 'Mécanique Auto', 91),
('3ème mécanique auto', 'Mécanique Auto', 92),
('4ème mécanique auto', 'Mécanique Auto', 93),
('1ère mécanique générale', 'Mécanique Générale', 100),
('2ème mécanique générale', 'Mécanique Générale', 101),
('3ème mécanique générale', 'Mécanique Générale', 102),
('4ème mécanique générale', 'Mécanique Générale', 103);
